apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: platter-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
