name: Deploy Platter to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: platter-cluster
  ECR_REPO_BACKEND: platter-backend
  ECR_REPO_FRONTEND: platter-frontend
  FRONTEND_API_URL: https://api.useplatter.ca

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG
          docker build --build-arg VITE_API_URL=$FRONTEND_API_URL -t $ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl apply -f k8s/backend-deployment.yml
          kubectl apply -f k8s/backend-service.yml
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/frontend-service.yml
          kubectl apply -f k8s/ingress.yml
          kubectl set image deployment/platter-backend-deployment platter-backend=$ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG

          kubectl set image deployment/platter-frontend-deployment platter-frontend=$ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG

          kubectl rollout status deployment/platter-backend-deployment
          kubectl rollout status deployment/platter-frontend-deployment
